# Ubuntu 14.04
image: ubuntu:trusty
# image: v4rtuw/ubuntu1404:0.0.1

# we use ROS indigo for now
variables:
  CI_ROS_DISTRO: indigo

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y wget
  - ./setup.sh
  
job:
  stage: build
  script:
  #  - rosdep install --from-paths . -i -y -r --rosdistro $CI_ROS_DISTRO
    - mkdir build
    - cd build
    - cmake ..
    - make -j8
