# we use ROS indigo for now

# Ubuntu 14.04
ubuntu-trusty:
  image: ubuntu:trusty
  variables:
    CI_ROS_DISTRO: indigo
  before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y wget
    - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
    - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y python-rosdep build-essential cmake
    - sudo rosdep init
    - rosdep update
  
  stage: build
  script:
    - rosdep install --from-paths . -i -y -r --rosdistro $CI_ROS_DISTRO
    - mkdir build
    - cd build
    - cmake ..
    - make -j8


# Ubuntu 16.04
ubuntu-xenial:
  image: ubuntu:trusty
  variables:
    CI_ROS_DISTRO: kinetic
  before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y wget
    - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list'
    - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y python-rosdep build-essential cmake
    - sudo rosdep init
    - rosdep update

  stage: build
  script:
    - rosdep install --from-paths . -i -y -r --rosdistro $CI_ROS_DISTRO
    - mkdir build
    - cd build
    - cmake ..
    - make -j8
