# Ubuntu 14.04
image: ubuntu:trusty

variables:
  CI_ROS_DISTRO: indigo

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y wget
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep build-essential cmake
  - sudo rosdep init
  - rosdep update
  - pwd

build:
  stage: build
  script:
    - pwd
    - ls
    - rosdep install --from-paths . -i -y -r --rosdistro $CI_ROS_DISTRO
    - mkdir build
    - pwd
    - ls
    - cd build
    - cmake ..
    - make -j8
